# Generated by Django 2.2.2 on 2019-12-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('time_and_id', models.TextField(blank=True, null=True)),
                ('data_set_id', models.TextField(blank=True, null=True)),
                ('thickness', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('tag_content', models.TextField(blank=True, null=True)),
                ('md5_val', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('message_head', models.TextField(blank=True, null=True)),
                ('message_body_data', models.BinaryField(blank=True, null=True)),
                ('message_body_param', models.TextField(blank=True, null=True)),
                ('run_alg_thickness', models.FloatField(blank=True, null=True)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thickness.DataTag')),
            ],
        ),
    ]
